use glutin;

///! These constants come from and are inspired by the pyprocessing project
///! (https://code.google.com/p/pyprocessing/source/browse/trunk/pyprocessing/constants.py)
///! with some slight adjustments

// shapes
// pub const POINTS = GL_POINTS;
// pub const LINES = GL_LINES;
// pub const TRIANGLES = GL_TRIANGLES;
// pub const TRIANGLE_FAN = GL_TRIANGLE_FAN;
// pub const TRIANGLE_STRIP = GL_TRIANGLE_STRIP;
// pub const QUADS = GL_QUADS;
// pub const QUAD_STRIP = GL_QUAD_STRIP;
pub const CLOSE: isize = 1;

/// Perlin noise table. Use it as a precomputed source of noise that emulates the
/// randomness found in natural processes.
pub const PERLIN: [isize; 512] = [
    151, 160, 137, 91, 90, 15, 131, 13, 201, 95, 96, 53, 194, 233, 7, 225, 140, 36, 103, 30, 69,
    142, 8, 99, 37, 240, 21, 10, 23, 190, 6, 148, 247, 120, 234, 75, 0, 26, 197, 62, 94, 252, 219,
    203, 117, 35, 11, 32, 57, 177, 33, 88, 237, 149, 56, 87, 174, 20, 125, 136, 171, 168, 68, 175,
    74, 165, 71, 134, 139, 48, 27, 166, 77, 146, 158, 231, 83, 111, 229, 122, 60, 211, 133, 230,
    220, 105, 92, 41, 55, 46, 245, 40, 244, 102, 143, 54, 65, 25, 63, 161, 1, 216, 80, 73, 209, 76,
    132, 187, 208, 89, 18, 169, 200, 196, 135, 130, 116, 188, 159, 86, 164, 100, 109, 198, 173,
    186, 3, 64, 52, 217, 226, 250, 124, 123, 5, 202, 38, 147, 118, 126, 255, 82, 85, 212, 207, 206,
    59, 227, 47, 16, 58, 17, 182, 189, 28, 42, 223, 183, 170, 213, 119, 248, 152, 2, 44, 154, 163,
    70, 221, 153, 101, 155, 167, 43, 172, 9, 129, 22, 39, 253, 19, 98, 108, 110, 79, 113, 224, 232,
    178, 185, 112, 104, 218, 246, 97, 228, 251, 34, 242, 193, 238, 210, 144, 12, 191, 179, 162,
    241, 81, 51, 145, 235, 249, 14, 239, 107, 49, 192, 214, 31, 181, 199, 106, 157, 184, 84, 204,
    176, 115, 121, 50, 45, 127, 4, 150, 254, 138, 236, 205, 93, 222, 114, 67, 29, 24, 72, 243, 141,
    128, 195, 78, 66, 215, 61, 156, 180, 151, 160, 137, 91, 90, 15, 131, 13, 201, 95, 96, 53, 194,
    233, 7, 225, 140, 36, 103, 30, 69, 142, 8, 99, 37, 240, 21, 10, 23, 190, 6, 148, 247, 120, 234,
    75, 0, 26, 197, 62, 94, 252, 219, 203, 117, 35, 11, 32, 57, 177, 33, 88, 237, 149, 56, 87, 174,
    20, 125, 136, 171, 168, 68, 175, 74, 165, 71, 134, 139, 48, 27, 166, 77, 146, 158, 231, 83,
    111, 229, 122, 60, 211, 133, 230, 220, 105, 92, 41, 55, 46, 245, 40, 244, 102, 143, 54, 65, 25,
    63, 161, 1, 216, 80, 73, 209, 76, 132, 187, 208, 89, 18, 169, 200, 196, 135, 130, 116, 188,
    159, 86, 164, 100, 109, 198, 173, 186, 3, 64, 52, 217, 226, 250, 124, 123, 5, 202, 38, 147,
    118, 126, 255, 82, 85, 212, 207, 206, 59, 227, 47, 16, 58, 17, 182, 189, 28, 42, 223, 183, 170,
    213, 119, 248, 152, 2, 44, 154, 163, 70, 221, 153, 101, 155, 167, 43, 172, 9, 129, 22, 39, 253,
    19, 98, 108, 110, 79, 113, 224, 232, 178, 185, 112, 104, 218, 246, 97, 228, 251, 34, 242, 193,
    238, 210, 144, 12, 191, 179, 162, 241, 81, 51, 145, 235, 249, 14, 239, 107, 49, 192, 214, 31,
    181, 199, 106, 157, 184, 84, 204, 176, 115, 121, 50, 45, 127, 4, 150, 254, 138, 236, 205, 93,
    222, 114, 67, 29, 24, 72, 243, 141, 128, 195, 78, 66, 215, 61, 156, 180,
];

/// The different mouse events that can be the result of user input.
#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug)]
pub enum MouseButton {
    Left,
    Right,
    Middle,
    Button4,
    Button5,
    Button6,
    Button7,
    Button8,
}

impl From<MouseButton> for glutin::event::MouseButton {
    fn from(btn: MouseButton) -> Self {
        match btn {
            MouseButton::Left => glutin::event::MouseButton::Left,
            MouseButton::Right => glutin::event::MouseButton::Right,
            MouseButton::Middle => glutin::event::MouseButton::Middle,
            MouseButton::Button4 => glutin::event::MouseButton::Other(4),
            MouseButton::Button5 => glutin::event::MouseButton::Other(5),
            MouseButton::Button6 => glutin::event::MouseButton::Other(6),
            MouseButton::Button7 => glutin::event::MouseButton::Other(7),
            MouseButton::Button8 => glutin::event::MouseButton::Other(8),
        }
    }
}

// needed to communicate across FFI boundary
pub fn mousebutton_from_u32(btn: u32) -> glutin::event::MouseButton {
    match btn {
        0 => glutin::event::MouseButton::Left,
        1 => glutin::event::MouseButton::Right,
        2 => glutin::event::MouseButton::Middle,
        3 => glutin::event::MouseButton::Other(4),
        4 => glutin::event::MouseButton::Other(5),
        5 => glutin::event::MouseButton::Other(6),
        6 => glutin::event::MouseButton::Other(7),
        7 => glutin::event::MouseButton::Other(8),
        _ => panic!("unsupported mouse button"),
    }
}

/// The different key events that can be the result of user input.
#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug)]
pub enum Key {
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    Num0,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Escape,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    Snapshot,
    Scroll,
    Pause,
    Insert,
    Home,
    Delete,
    End,
    PageDown,
    PageUp,
    Left,
    Up,
    Right,
    Down,
    Back,
    Return,
    Space,
    Compose,
    Numlock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    AbntC1,
    AbntC2,
    Add,
    Apostrophe,
    Apps,
    At,
    Ax,
    Backslash,
    Calculator,
    Capital,
    Colon,
    Comma,
    Convert,
    Decimal,
    Divide,
    Equals,
    Grave,
    Kana,
    Kanji,
    LAlt,
    LBracket,
    LControl,
    //LMenu,
    LShift,
    LWin,
    Mail,
    MediaSelect,
    MediaStop,
    Minus,
    Multiply,
    Mute,
    MyComputer,
    NavigateForward,
    NavigateBackward,
    NextTrack,
    NoConvert,
    NumpadComma,
    NumpadEnter,
    NumpadEquals,
    OEM102,
    Period,
    PlayPause,
    Power,
    PrevTrack,
    RAlt,
    RBracket,
    RControl,
    //RMenu,
    RShift,
    RWin,
    Semicolon,
    Slash,
    Sleep,
    Stop,
    Subtract,
    Sysrq,
    Tab,
    Underline,
    Unlabeled,
    VolumeDown,
    VolumeUp,
    Wake,
    WebBack,
    WebFavorites,
    WebForward,
    WebHome,
    WebRefresh,
    WebSearch,
    WebStop,
    Yen,
}

impl From<Key> for glutin::event::VirtualKeyCode {
    fn from(btn: Key) -> Self {
        match btn {
            Key::Num1 => glutin::event::VirtualKeyCode::Key1,
            Key::Num2 => glutin::event::VirtualKeyCode::Key2,
            Key::Num3 => glutin::event::VirtualKeyCode::Key3,
            Key::Num4 => glutin::event::VirtualKeyCode::Key4,
            Key::Num5 => glutin::event::VirtualKeyCode::Key5,
            Key::Num6 => glutin::event::VirtualKeyCode::Key6,
            Key::Num7 => glutin::event::VirtualKeyCode::Key7,
            Key::Num8 => glutin::event::VirtualKeyCode::Key8,
            Key::Num9 => glutin::event::VirtualKeyCode::Key9,
            Key::Num0 => glutin::event::VirtualKeyCode::Key0,
            Key::A => glutin::event::VirtualKeyCode::A,
            Key::B => glutin::event::VirtualKeyCode::B,
            Key::C => glutin::event::VirtualKeyCode::C,
            Key::D => glutin::event::VirtualKeyCode::D,
            Key::E => glutin::event::VirtualKeyCode::E,
            Key::F => glutin::event::VirtualKeyCode::F,
            Key::G => glutin::event::VirtualKeyCode::G,
            Key::H => glutin::event::VirtualKeyCode::H,
            Key::I => glutin::event::VirtualKeyCode::I,
            Key::J => glutin::event::VirtualKeyCode::J,
            Key::K => glutin::event::VirtualKeyCode::K,
            Key::L => glutin::event::VirtualKeyCode::L,
            Key::M => glutin::event::VirtualKeyCode::M,
            Key::N => glutin::event::VirtualKeyCode::N,
            Key::O => glutin::event::VirtualKeyCode::O,
            Key::P => glutin::event::VirtualKeyCode::P,
            Key::Q => glutin::event::VirtualKeyCode::Q,
            Key::R => glutin::event::VirtualKeyCode::R,
            Key::S => glutin::event::VirtualKeyCode::S,
            Key::T => glutin::event::VirtualKeyCode::T,
            Key::U => glutin::event::VirtualKeyCode::U,
            Key::V => glutin::event::VirtualKeyCode::V,
            Key::W => glutin::event::VirtualKeyCode::W,
            Key::X => glutin::event::VirtualKeyCode::X,
            Key::Y => glutin::event::VirtualKeyCode::Y,
            Key::Z => glutin::event::VirtualKeyCode::Z,
            Key::Escape => glutin::event::VirtualKeyCode::Escape,
            Key::F1 => glutin::event::VirtualKeyCode::F1,
            Key::F2 => glutin::event::VirtualKeyCode::F2,
            Key::F3 => glutin::event::VirtualKeyCode::F3,
            Key::F4 => glutin::event::VirtualKeyCode::F4,
            Key::F5 => glutin::event::VirtualKeyCode::F5,
            Key::F6 => glutin::event::VirtualKeyCode::F6,
            Key::F7 => glutin::event::VirtualKeyCode::F7,
            Key::F8 => glutin::event::VirtualKeyCode::F8,
            Key::F9 => glutin::event::VirtualKeyCode::F9,
            Key::F10 => glutin::event::VirtualKeyCode::F10,
            Key::F11 => glutin::event::VirtualKeyCode::F11,
            Key::F12 => glutin::event::VirtualKeyCode::F12,
            Key::F13 => glutin::event::VirtualKeyCode::F13,
            Key::F14 => glutin::event::VirtualKeyCode::F14,
            Key::F15 => glutin::event::VirtualKeyCode::F15,
            Key::Snapshot => glutin::event::VirtualKeyCode::Snapshot,
            Key::Scroll => glutin::event::VirtualKeyCode::Scroll,
            Key::Pause => glutin::event::VirtualKeyCode::Pause,
            Key::Insert => glutin::event::VirtualKeyCode::Insert,
            Key::Home => glutin::event::VirtualKeyCode::Home,
            Key::Delete => glutin::event::VirtualKeyCode::Delete,
            Key::End => glutin::event::VirtualKeyCode::End,
            Key::PageDown => glutin::event::VirtualKeyCode::PageDown,
            Key::PageUp => glutin::event::VirtualKeyCode::PageUp,
            Key::Left => glutin::event::VirtualKeyCode::Left,
            Key::Up => glutin::event::VirtualKeyCode::Up,
            Key::Right => glutin::event::VirtualKeyCode::Right,
            Key::Down => glutin::event::VirtualKeyCode::Down,
            Key::Back => glutin::event::VirtualKeyCode::Back,
            Key::Return => glutin::event::VirtualKeyCode::Return,
            Key::Space => glutin::event::VirtualKeyCode::Space,
            Key::Compose => glutin::event::VirtualKeyCode::Compose,
            Key::Numlock => glutin::event::VirtualKeyCode::Numlock,
            Key::Numpad0 => glutin::event::VirtualKeyCode::Numpad0,
            Key::Numpad1 => glutin::event::VirtualKeyCode::Numpad1,
            Key::Numpad2 => glutin::event::VirtualKeyCode::Numpad2,
            Key::Numpad3 => glutin::event::VirtualKeyCode::Numpad3,
            Key::Numpad4 => glutin::event::VirtualKeyCode::Numpad4,
            Key::Numpad5 => glutin::event::VirtualKeyCode::Numpad5,
            Key::Numpad6 => glutin::event::VirtualKeyCode::Numpad6,
            Key::Numpad7 => glutin::event::VirtualKeyCode::Numpad7,
            Key::Numpad8 => glutin::event::VirtualKeyCode::Numpad8,
            Key::Numpad9 => glutin::event::VirtualKeyCode::Numpad9,
            Key::AbntC1 => glutin::event::VirtualKeyCode::AbntC1,
            Key::AbntC2 => glutin::event::VirtualKeyCode::AbntC2,
            Key::Add => glutin::event::VirtualKeyCode::Add,
            Key::Apostrophe => glutin::event::VirtualKeyCode::Apostrophe,
            Key::Apps => glutin::event::VirtualKeyCode::Apps,
            Key::At => glutin::event::VirtualKeyCode::At,
            Key::Ax => glutin::event::VirtualKeyCode::Ax,
            Key::Backslash => glutin::event::VirtualKeyCode::Backslash,
            Key::Calculator => glutin::event::VirtualKeyCode::Calculator,
            Key::Capital => glutin::event::VirtualKeyCode::Capital,
            Key::Colon => glutin::event::VirtualKeyCode::Colon,
            Key::Comma => glutin::event::VirtualKeyCode::Comma,
            Key::Convert => glutin::event::VirtualKeyCode::Convert,
            Key::Decimal => glutin::event::VirtualKeyCode::Decimal,
            Key::Divide => glutin::event::VirtualKeyCode::Divide,
            Key::Equals => glutin::event::VirtualKeyCode::Equals,
            Key::Grave => glutin::event::VirtualKeyCode::Grave,
            Key::Kana => glutin::event::VirtualKeyCode::Kana,
            Key::Kanji => glutin::event::VirtualKeyCode::Kanji,
            Key::LAlt => glutin::event::VirtualKeyCode::LAlt,
            Key::LBracket => glutin::event::VirtualKeyCode::LBracket,
            Key::LControl => glutin::event::VirtualKeyCode::LControl,
            //Key::LMenu => glutin::event::VirtualKeyCode::LMenu,
            Key::LShift => glutin::event::VirtualKeyCode::LShift,
            Key::LWin => glutin::event::VirtualKeyCode::LWin,
            Key::Mail => glutin::event::VirtualKeyCode::Mail,
            Key::MediaSelect => glutin::event::VirtualKeyCode::MediaSelect,
            Key::MediaStop => glutin::event::VirtualKeyCode::MediaStop,
            Key::Minus => glutin::event::VirtualKeyCode::Minus,
            Key::Multiply => glutin::event::VirtualKeyCode::Multiply,
            Key::Mute => glutin::event::VirtualKeyCode::Mute,
            Key::MyComputer => glutin::event::VirtualKeyCode::MyComputer,
            Key::NavigateForward => glutin::event::VirtualKeyCode::NavigateForward,
            Key::NavigateBackward => glutin::event::VirtualKeyCode::NavigateBackward,
            Key::NextTrack => glutin::event::VirtualKeyCode::NextTrack,
            Key::NoConvert => glutin::event::VirtualKeyCode::NoConvert,
            Key::NumpadComma => glutin::event::VirtualKeyCode::NumpadComma,
            Key::NumpadEnter => glutin::event::VirtualKeyCode::NumpadEnter,
            Key::NumpadEquals => glutin::event::VirtualKeyCode::NumpadEquals,
            Key::OEM102 => glutin::event::VirtualKeyCode::OEM102,
            Key::Period => glutin::event::VirtualKeyCode::Period,
            Key::PlayPause => glutin::event::VirtualKeyCode::PlayPause,
            Key::Power => glutin::event::VirtualKeyCode::Power,
            Key::PrevTrack => glutin::event::VirtualKeyCode::PrevTrack,
            Key::RAlt => glutin::event::VirtualKeyCode::RAlt,
            Key::RBracket => glutin::event::VirtualKeyCode::RBracket,
            Key::RControl => glutin::event::VirtualKeyCode::RControl,
            //Key::RMenu => glutin::event::VirtualKeyCode::RMenu,
            Key::RShift => glutin::event::VirtualKeyCode::RShift,
            Key::RWin => glutin::event::VirtualKeyCode::RWin,
            Key::Semicolon => glutin::event::VirtualKeyCode::Semicolon,
            Key::Slash => glutin::event::VirtualKeyCode::Slash,
            Key::Sleep => glutin::event::VirtualKeyCode::Sleep,
            Key::Stop => glutin::event::VirtualKeyCode::Stop,
            Key::Subtract => glutin::event::VirtualKeyCode::Subtract,
            Key::Sysrq => glutin::event::VirtualKeyCode::Sysrq,
            Key::Tab => glutin::event::VirtualKeyCode::Tab,
            Key::Underline => glutin::event::VirtualKeyCode::Underline,
            Key::Unlabeled => glutin::event::VirtualKeyCode::Unlabeled,
            Key::VolumeDown => glutin::event::VirtualKeyCode::VolumeDown,
            Key::VolumeUp => glutin::event::VirtualKeyCode::VolumeUp,
            Key::Wake => glutin::event::VirtualKeyCode::Wake,
            Key::WebBack => glutin::event::VirtualKeyCode::WebBack,
            Key::WebFavorites => glutin::event::VirtualKeyCode::WebFavorites,
            Key::WebForward => glutin::event::VirtualKeyCode::WebForward,
            Key::WebHome => glutin::event::VirtualKeyCode::WebHome,
            Key::WebRefresh => glutin::event::VirtualKeyCode::WebRefresh,
            Key::WebSearch => glutin::event::VirtualKeyCode::WebSearch,
            Key::WebStop => glutin::event::VirtualKeyCode::WebStop,
            Key::Yen => glutin::event::VirtualKeyCode::Yen,
        }
    }
}

// needed to communicate across FFI boundary
pub fn keycode_from_u32(btn: u32) -> glutin::event::VirtualKeyCode {
    match btn {
        0 => glutin::event::VirtualKeyCode::Key1,
        1 => glutin::event::VirtualKeyCode::Key2,
        2 => glutin::event::VirtualKeyCode::Key3,
        3 => glutin::event::VirtualKeyCode::Key4,
        4 => glutin::event::VirtualKeyCode::Key5,
        5 => glutin::event::VirtualKeyCode::Key6,
        6 => glutin::event::VirtualKeyCode::Key7,
        7 => glutin::event::VirtualKeyCode::Key8,
        8 => glutin::event::VirtualKeyCode::Key9,
        9 => glutin::event::VirtualKeyCode::Key0,
        10 => glutin::event::VirtualKeyCode::A,
        11 => glutin::event::VirtualKeyCode::B,
        12 => glutin::event::VirtualKeyCode::C,
        13 => glutin::event::VirtualKeyCode::D,
        14 => glutin::event::VirtualKeyCode::E,
        15 => glutin::event::VirtualKeyCode::F,
        16 => glutin::event::VirtualKeyCode::G,
        17 => glutin::event::VirtualKeyCode::H,
        18 => glutin::event::VirtualKeyCode::I,
        19 => glutin::event::VirtualKeyCode::J,
        20 => glutin::event::VirtualKeyCode::K,
        21 => glutin::event::VirtualKeyCode::L,
        22 => glutin::event::VirtualKeyCode::M,
        23 => glutin::event::VirtualKeyCode::N,
        24 => glutin::event::VirtualKeyCode::O,
        25 => glutin::event::VirtualKeyCode::P,
        26 => glutin::event::VirtualKeyCode::Q,
        27 => glutin::event::VirtualKeyCode::R,
        28 => glutin::event::VirtualKeyCode::S,
        29 => glutin::event::VirtualKeyCode::T,
        30 => glutin::event::VirtualKeyCode::U,
        31 => glutin::event::VirtualKeyCode::V,
        32 => glutin::event::VirtualKeyCode::W,
        33 => glutin::event::VirtualKeyCode::X,
        34 => glutin::event::VirtualKeyCode::Y,
        35 => glutin::event::VirtualKeyCode::Z,
        36 => glutin::event::VirtualKeyCode::Escape,
        37 => glutin::event::VirtualKeyCode::F1,
        38 => glutin::event::VirtualKeyCode::F2,
        39 => glutin::event::VirtualKeyCode::F3,
        40 => glutin::event::VirtualKeyCode::F4,
        41 => glutin::event::VirtualKeyCode::F5,
        42 => glutin::event::VirtualKeyCode::F6,
        43 => glutin::event::VirtualKeyCode::F7,
        44 => glutin::event::VirtualKeyCode::F8,
        45 => glutin::event::VirtualKeyCode::F9,
        46 => glutin::event::VirtualKeyCode::F10,
        47 => glutin::event::VirtualKeyCode::F11,
        48 => glutin::event::VirtualKeyCode::F12,
        49 => glutin::event::VirtualKeyCode::F13,
        50 => glutin::event::VirtualKeyCode::F14,
        51 => glutin::event::VirtualKeyCode::F15,
        52 => glutin::event::VirtualKeyCode::Snapshot,
        53 => glutin::event::VirtualKeyCode::Scroll,
        54 => glutin::event::VirtualKeyCode::Pause,
        55 => glutin::event::VirtualKeyCode::Insert,
        56 => glutin::event::VirtualKeyCode::Home,
        57 => glutin::event::VirtualKeyCode::Delete,
        58 => glutin::event::VirtualKeyCode::End,
        59 => glutin::event::VirtualKeyCode::PageDown,
        60 => glutin::event::VirtualKeyCode::PageUp,
        61 => glutin::event::VirtualKeyCode::Left,
        62 => glutin::event::VirtualKeyCode::Up,
        63 => glutin::event::VirtualKeyCode::Right,
        64 => glutin::event::VirtualKeyCode::Down,
        65 => glutin::event::VirtualKeyCode::Back,
        66 => glutin::event::VirtualKeyCode::Return,
        67 => glutin::event::VirtualKeyCode::Space,
        68 => glutin::event::VirtualKeyCode::Compose,
        69 => glutin::event::VirtualKeyCode::Numlock,
        70 => glutin::event::VirtualKeyCode::Numpad0,
        71 => glutin::event::VirtualKeyCode::Numpad1,
        72 => glutin::event::VirtualKeyCode::Numpad2,
        73 => glutin::event::VirtualKeyCode::Numpad3,
        74 => glutin::event::VirtualKeyCode::Numpad4,
        75 => glutin::event::VirtualKeyCode::Numpad5,
        76 => glutin::event::VirtualKeyCode::Numpad6,
        77 => glutin::event::VirtualKeyCode::Numpad7,
        78 => glutin::event::VirtualKeyCode::Numpad8,
        79 => glutin::event::VirtualKeyCode::Numpad9,
        80 => glutin::event::VirtualKeyCode::AbntC1,
        81 => glutin::event::VirtualKeyCode::AbntC2,
        82 => glutin::event::VirtualKeyCode::Add,
        83 => glutin::event::VirtualKeyCode::Apostrophe,
        84 => glutin::event::VirtualKeyCode::Apps,
        85 => glutin::event::VirtualKeyCode::At,
        86 => glutin::event::VirtualKeyCode::Ax,
        87 => glutin::event::VirtualKeyCode::Backslash,
        88 => glutin::event::VirtualKeyCode::Calculator,
        89 => glutin::event::VirtualKeyCode::Capital,
        90 => glutin::event::VirtualKeyCode::Colon,
        91 => glutin::event::VirtualKeyCode::Comma,
        92 => glutin::event::VirtualKeyCode::Convert,
        93 => glutin::event::VirtualKeyCode::Decimal,
        94 => glutin::event::VirtualKeyCode::Divide,
        95 => glutin::event::VirtualKeyCode::Equals,
        96 => glutin::event::VirtualKeyCode::Grave,
        97 => glutin::event::VirtualKeyCode::Kana,
        98 => glutin::event::VirtualKeyCode::Kanji,
        99 => glutin::event::VirtualKeyCode::LAlt,
        100 => glutin::event::VirtualKeyCode::LBracket,
        101 => glutin::event::VirtualKeyCode::LControl,
        102 => glutin::event::VirtualKeyCode::LShift,
        103 => glutin::event::VirtualKeyCode::LWin,
        104 => glutin::event::VirtualKeyCode::Mail,
        105 => glutin::event::VirtualKeyCode::MediaSelect,
        106 => glutin::event::VirtualKeyCode::MediaStop,
        107 => glutin::event::VirtualKeyCode::Minus,
        108 => glutin::event::VirtualKeyCode::Multiply,
        109 => glutin::event::VirtualKeyCode::Mute,
        110 => glutin::event::VirtualKeyCode::MyComputer,
        111 => glutin::event::VirtualKeyCode::NavigateForward,
        112 => glutin::event::VirtualKeyCode::NavigateBackward,
        113 => glutin::event::VirtualKeyCode::NextTrack,
        114 => glutin::event::VirtualKeyCode::NoConvert,
        115 => glutin::event::VirtualKeyCode::NumpadComma,
        116 => glutin::event::VirtualKeyCode::NumpadEnter,
        117 => glutin::event::VirtualKeyCode::NumpadEquals,
        118 => glutin::event::VirtualKeyCode::OEM102,
        119 => glutin::event::VirtualKeyCode::Period,
        120 => glutin::event::VirtualKeyCode::PlayPause,
        121 => glutin::event::VirtualKeyCode::Power,
        122 => glutin::event::VirtualKeyCode::PrevTrack,
        123 => glutin::event::VirtualKeyCode::RAlt,
        124 => glutin::event::VirtualKeyCode::RBracket,
        125 => glutin::event::VirtualKeyCode::RControl,
        126 => glutin::event::VirtualKeyCode::RShift,
        127 => glutin::event::VirtualKeyCode::RWin,
        128 => glutin::event::VirtualKeyCode::Semicolon,
        129 => glutin::event::VirtualKeyCode::Slash,
        130 => glutin::event::VirtualKeyCode::Sleep,
        131 => glutin::event::VirtualKeyCode::Stop,
        132 => glutin::event::VirtualKeyCode::Subtract,
        133 => glutin::event::VirtualKeyCode::Sysrq,
        134 => glutin::event::VirtualKeyCode::Tab,
        135 => glutin::event::VirtualKeyCode::Underline,
        136 => glutin::event::VirtualKeyCode::Unlabeled,
        137 => glutin::event::VirtualKeyCode::VolumeDown,
        138 => glutin::event::VirtualKeyCode::VolumeUp,
        139 => glutin::event::VirtualKeyCode::Wake,
        140 => glutin::event::VirtualKeyCode::WebBack,
        141 => glutin::event::VirtualKeyCode::WebFavorites,
        142 => glutin::event::VirtualKeyCode::WebForward,
        143 => glutin::event::VirtualKeyCode::WebHome,
        144 => glutin::event::VirtualKeyCode::WebRefresh,
        145 => glutin::event::VirtualKeyCode::WebSearch,
        146 => glutin::event::VirtualKeyCode::WebStop,
        147 => glutin::event::VirtualKeyCode::Yen,
        _ => panic!("unsupported key code"),
    }
}
